# Generated by Django 5.0.3 on 2024-03-22 08:17

import crm.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_for', models.CharField(choices=[('E', 'سالمند'), ('P', 'مددجو'), ('K', 'کودک')], max_length=1)),
                ('relationship_with_patient', models.CharField(choices=[('S', 'خودشان'), ('C', 'فرزند'), ('P', 'همسر'), ('O', 'سایر')], max_length=1)),
                ('shift', models.CharField(choices=[('D', 'روزانه'), ('N', 'شبانه'), ('B', 'شبانه روزی'), ('O', 'سایر')], max_length=1)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('shift_start', models.PositiveSmallIntegerField(default=8)),
                ('shift_end', models.PositiveSmallIntegerField(default=18)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('include_holidays', models.BooleanField(default=True)),
                ('personnel_monthly_salary', models.IntegerField(default=0)),
                ('personnel_salary_payment_time', models.CharField(choices=[('S', 'ابتدای ماه'), ('E', 'انتهای ماه'), ('O', 'سایر')], max_length=1)),
                ('healthcare_franchise_amount', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost', models.BigIntegerField()),
                ('discount', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, validators=[crm.validators.national_code, crm.validators.blacklist_national_codes])),
                ('firstname', models.CharField(max_length=50, validators=[crm.validators.trim_string])),
                ('lastname', models.CharField(max_length=50, validators=[crm.validators.trim_string])),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1)),
                ('birthdate', models.CharField(max_length=10)),
                ('people_type', models.CharField(choices=[('PSN', 'پرسنل'), ('CLI', 'کارفرما'), ('CSE', 'مددجو')], max_length=3)),
                ('contract_date', models.DateField(null=True)),
                ('end_contract_date', models.DateField(null=True)),
                ('personnel_role', models.CharField(choices=[('DCTR', 'پزشک'), ('NRS', 'پرستار'), ('PNRS', 'بهیار'), ('ANRS', 'کمک بهیار'), ('HCRE', 'مراقب')], max_length=4)),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('paid_at', models.CharField(max_length=10)),
                ('note', models.TextField(null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contract')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_payments', to='crm.people')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_payments', to='crm.people')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_orders', to='crm.people'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='crm.people'),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_orders', to='crm.people'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contracts', to='crm.people'),
        ),
        migrations.AddField(
            model_name='contract',
            name='patients',
            field=models.ManyToManyField(related_name='patient_contracts', to='crm.people'),
        ),
        migrations.AddField(
            model_name='contract',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_contracts', to='crm.people'),
        ),
        migrations.AddField(
            model_name='contract',
            name='referral_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_contracts', to='crm.people'),
        ),
        migrations.CreateModel(
            name='PeopleDetailedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(choices=[('A', 'آدرس'), ('P', 'شماره تماس'), ('C', 'کارت بانکی')], max_length=1)),
                ('address', models.CharField(max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('card_number', models.CharField(max_length=16, null=True)),
                ('note', models.TextField(null=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='crm.people')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='service_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.peopledetailedinfo'),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.peopledetailedinfo'),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.referral'),
        ),
        migrations.AddField(
            model_name='contract',
            name='referral_other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.referral'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('base_price', models.BigIntegerField()),
                ('healthcare_franchise', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.service')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.service'),
        ),
    ]
