# Generated by Django 5.0.3 on 2024-05-31 09:14

import crm.models
import crm.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_without_discount', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('healthcare_franchise', models.BigIntegerField()),
                ('personnel_fee', models.BigIntegerField()),
                ('personnel_paid', models.BigIntegerField()),
                ('client_paid', models.BigIntegerField()),
                ('personnel_debt', models.BigIntegerField()),
                ('client_debt', models.BigIntegerField()),
            ],
            options={
                'db_table': 'order_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[crm.validators.national_code])),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_at', crm.models.JDateField(max_length=10, validators=[crm.validators.jdate_string_validator])),
                ('care_for', models.CharField(choices=[('E', 'سالمند'), ('P', 'مددجو'), ('K', 'کودک')], max_length=1)),
                ('relationship_with_patient', models.CharField(choices=[('S', 'خودشان'), ('C', 'فرزند'), ('P', 'همسر'), ('O', 'سایر')], max_length=1)),
                ('shift', models.CharField(choices=[('D', 'روزانه'), ('N', 'شبانه'), ('B', 'شبانه روزی'), ('O', 'سایر')], max_length=1)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('shift_start', models.PositiveSmallIntegerField(default=8)),
                ('shift_end', models.PositiveSmallIntegerField(default=18)),
                ('start', crm.models.JDateField(max_length=10, validators=[crm.validators.jdate_string_validator])),
                ('start_hour', models.TimeField()),
                ('end', crm.models.JDateField(max_length=10, validators=[crm.validators.jdate_string_validator])),
                ('end_hour', models.TimeField()),
                ('include_holidays', models.BooleanField(default=True)),
                ('personnel_monthly_salary', models.IntegerField(default=0)),
                ('personnel_salary_payment_time', models.CharField(choices=[('S', 'ابتدای ماه'), ('E', 'انتهای ماه'), ('O', 'سایر')], max_length=1)),
                ('healthcare_franchise_amount', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_at', crm.models.JDateField(max_length=10, validators=[crm.validators.jdate_string_validator])),
                ('discount', models.BigIntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', crm.models.JDateField(max_length=10, validators=[crm.validators.jdate_string_validator])),
                ('national_code', models.CharField(max_length=10, validators=[crm.validators.national_code, crm.validators.blacklist_national_codes])),
                ('firstname', models.CharField(max_length=50, validators=[crm.validators.trim_string])),
                ('lastname', models.CharField(max_length=50, validators=[crm.validators.trim_string])),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1)),
                ('birthdate', models.CharField(max_length=10)),
                ('contract_date', models.CharField(blank=True, max_length=10, null=True)),
                ('end_contract_date', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.catalog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', crm.models.JDateField(max_length=10, validators=[crm.validators.jdate_string_validator])),
                ('amount', models.BigIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.contract')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_payments', to='crm.people')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_payments', to='crm.people')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_orders', to='crm.people'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='crm.people'),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_orders', to='crm.people'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contracts', to='crm.people'),
        ),
        migrations.AddField(
            model_name='contract',
            name='patients',
            field=models.ManyToManyField(related_name='patient_contracts', to='crm.people'),
        ),
        migrations.AddField(
            model_name='contract',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_contracts', to='crm.people'),
        ),
        migrations.AddField(
            model_name='contract',
            name='referral_people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_contracts', to='crm.people'),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('called_at', crm.models.JDateField(max_length=10, validators=[crm.validators.jdate_string_validator])),
                ('from_number', models.CharField(blank=True, max_length=15, null=True)),
                ('to_number', models.CharField(blank=True, max_length=15, null=True)),
                ('duration_in_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('call_direction', models.CharField(choices=[('INC', 'ورودی'), ('OUT', 'خروجی')], max_length=3)),
                ('response_status', models.CharField(choices=[('ANS', 'پاسخ داده شده'), ('REJ', 'رد شده')], max_length=3)),
                ('note', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.contract')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
                ('from_people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_calls', to='crm.people')),
                ('to_people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_calls', to='crm.people')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeopleDetailedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail_type', models.CharField(choices=[('A', 'آدرس'), ('P', 'شماره تماس'), ('C', 'کارت بانکی')], max_length=1)),
                ('value', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='crm.people')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='service_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.peopledetailedinfo'),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.peopledetailedinfo'),
        ),
        migrations.CreateModel(
            name='PeopleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.catalog')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.people')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='people',
            name='roles',
            field=models.ManyToManyField(related_name='people_roles', through='crm.PeopleRole', to='crm.catalog'),
        ),
        migrations.CreateModel(
            name='PeopleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.catalog')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.people')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='people',
            name='types',
            field=models.ManyToManyField(related_name='people_types', through='crm.PeopleType', to='crm.catalog'),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.referral'),
        ),
        migrations.AddField(
            model_name='contract',
            name='referral_other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.referral'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('base_price', models.BigIntegerField()),
                ('healthcare_franchise', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost', models.PositiveBigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(through='crm.OrderServices', to='crm.service'),
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.catalog')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.people')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='people',
            name='service_locations',
            field=models.ManyToManyField(related_name='people_service_locations', through='crm.ServiceLocation', to='crm.catalog'),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.catalog')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.people')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='people',
            name='specifications',
            field=models.ManyToManyField(related_name='people_specifications', through='crm.Specification', to='crm.catalog'),
        ),
    ]
