# Generated by Django 5.0.3 on 2024-03-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='personnel_role',
            field=models.CharField(choices=[('DCTR', 'پزشک'), ('NRS', 'پرستار'), ('PNRS', 'بهیار'), ('ANRS', 'کمک بهیار'), ('HCRE', 'مراقب')], max_length=4, null=True),
        ),
    ]
