# Generated by Django 5.0.3 on 2024-03-22 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_people_personnel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='contract_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='end_contract_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='TagSpecefication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.tagspecefication')),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='specifications',
            field=models.ManyToManyField(to='crm.tagspecefication'),
        ),
    ]
