# Generated by Django 5.0.3 on 2024-06-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_people_father_name_people_minimum_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='peopletype',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='peopletype',
            name='people',
        ),
        migrations.RemoveField(
            model_name='people',
            name='types',
        ),
        migrations.RemoveField(
            model_name='servicelocation',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='servicelocation',
            name='people',
        ),
        migrations.RemoveField(
            model_name='people',
            name='service_locations',
        ),
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='address',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='overall_rate',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PeopleRole',
        ),
        migrations.DeleteModel(
            name='PeopleType',
        ),
        migrations.DeleteModel(
            name='ServiceLocation',
        ),
    ]
