# Generated by Django 5.0.3 on 2024-03-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_order_service_orderservices_order_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='service',
            new_name='services',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
    ]
