# Generated by Django 5.0.3 on 2024-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_people_roles_remove_peopletype_catalog_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='specification',
            constraint=models.UniqueConstraint(fields=('people', 'catalog'), name='unique_specification'),
        ),
    ]
