# Generated by Django 5.0.3 on 2024-03-25 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_service_order_services_remove_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='referral_other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.referral'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='referral_people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_contracts', to='crm.people'),
        ),
    ]
