# Generated by Django 5.0.3 on 2024-03-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_contract_referral_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_hour',
            field=models.TimeField(default="12:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='start_hour',
            field=models.TimeField(default="09:00"),
            preserve_default=False,
        ),
    ]
