# Generated by Django 5.0.3 on 2024-03-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_contract_end_hour_contract_start_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_without_discount', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('healthcare_franchise', models.BigIntegerField()),
                ('personnel_fee', models.BigIntegerField()),
                ('personnel_paid', models.BigIntegerField()),
                ('client_paid', models.BigIntegerField()),
                ('personnel_debt', models.BigIntegerField()),
                ('client_debt', models.BigIntegerField()),
            ],
            options={
                'db_table': 'order_payment',
                'managed': False,
            },
        ),
    ]
