# Generated by Django 5.0.3 on 2024-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_orderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_type',
            field=models.CharField(choices=[('PSN', 'پرسنل'), ('CLI', 'کارفرما'), ('PNT', 'مددجو')], max_length=3),
        ),
    ]
