# Generated by Django 5.0.3 on 2024-04-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_call_note_alter_people_people_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopledetailedinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
