# Generated by Django 5.0.3 on 2024-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_blacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopledetailedinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='peopledetailedinfo',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='peopledetailedinfo',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='peopledetailedinfo',
            name='value',
            field=models.CharField(default='A', max_length=250),
            preserve_default=False,
        ),
    ]
