# Generated by Django 5.0.3 on 2024-05-20 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_remove_peopledetailedinfo_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('rate', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.catalog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='people',
            name='specifications',
            field=models.ManyToManyField(blank=True, to='crm.catalog'),
        ),
        migrations.DeleteModel(
            name='TagSpecefication',
        ),
    ]
