# Generated by Django 5.0.3 on 2024-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_catalog_alter_people_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
